spring:
  profiles.active: dev

  # Configuración de la bb dd
  datasource:
    url:
    username:
    password:
    driver-class-name:
  jpa:
    hibernate.ddl-auto: update

server:
  port: 8040
  servlet.context-path: /dnd-api