INSERT IGNORE INTO monster_types(name, description) VALUES
("Humanoide", "Constituyen la mayor parte de las culturas de los mundos de D&D, tanto salvajes como civilizadas. Este tipo incluye a los humanos y a una enorme variedad de otras especies. Son bípedos, conocen algún idioma y tienen alguna forma de estructura social. Muy pocos poseen capacidades mágicas innatas, aunque la mayoría pueden aprender a lanzar conjuros. Las razas de humanoides más comunes suelen ser las típicas de los personajes jugadores: humanos, elfos, enanos y medianos. Sin embargo, existen otras razas de humanoides, casi tan numerosas como las anteriores, pero mucho más salvajes, brutales, y, casi siempre, malvadas: los trasgos (goblins, hobgoblins y osgos), los orcos, los gnolls, los hombres lagarto y los kobolds"),

("Infernal", "Criaturas retorcidas naturales de los Planos Inferiores. Algunos sirven a los dioses, aunque la mayoría trabajan para los archidiablos y los príncipes demonio. Ciertosmagos y sacerdotes malvados intentan invocar infernales al mundo material para que cumplan sus órdenes. Si un celestial maligno es una rara avis, un infernal bueno es prácticamente inconcebible. Los demonios, diablos, sabuesos infernales, rakshasas y yugoloths son todos ellos infernales"),

("Monstruosidad", "Monstruos en el sentido más literal de la palabra: criaturas aterradoras que no son ni normales ni naturales y prácticamente nunca bondadosas. Algunas son el resultado de experimentos mágicos que han salido mal (como los osos lechuza), mientras que otras son producto de horribles maldiciones (como los minotauros y los yuan-ti). Se resisten a cualquier taxonomía, por lo que este tipo suele servir como un cajón de sastre en el que meter a todas aquellas criaturas que no encajan en ningún otro"),

("Muerto Viviente", "Criaturas que antaño estuvieron vivas, pero que ahora se alzan en una horrible parodia de la vida, víctimas de la nigromancia o de alguna maldición impía. Tanto los cadáveres animados, como los vampiros y los zombis, como los espíritus incorpóreos, como los fantasmas y espectros, son muertos vivientes"),

("Planta", "No son, en este contexto, simple flora, sino criaturas del reino vegetal. La mayoría son capaces de desplazarse y algunas son carnívoras. Las plantas por excelencia son las brozas movedizas y los ents. Las criaturas fúngicas, como las esporas de gas y los micónidos, también entran en esta categoría"),

("Aberración", "Son seres de naturaleza completamente alienígena. Muchos de ellos poseen habilidades mágicas innatas que no provienen de las fuerzas místicas del mundo, sino de la propia mente de la criatura. Las aberraciones por antonomasia son los aboleths, los azotamentes, los contempladores y los slaads"),

("Autómata", "No nacen de forma natural, sino que son construidos. Algunos han sido programados por sus creadores para obedecer unas instrucciones muy sencillas, mientras que otros tienen consciencia y son capaces de pensar por sí mismos. Los gólems son los autómatas arquetípicos. Muchas criaturas nativas del Plano Exterior de Mechanus, como los modrons, son autómatas creados a partir de la materia prima de su plano natal. Son producto de la voluntad de seres superiores"),

('Bestia', 'Criaturas no humanoides que forman parte del ecosistema. Algunas poseen poderes mágicos, pero la mayoría no son inteligentes y carecen de sociedad o idioma alguno. Ejemplos de bestias son los animales corrientes, los dinosaurios y las versiones gigantescas de ciertos animales'),

('Celestial', 'Criaturas nativas de los Planos Superiores. Muchas de ellas sirven a los dioses, como sus mensajeros y agentes en el reino mortal y a lo largo y ancho de los planos. Los celestiales son buenos por naturaleza, así que aquellos individuos excepcionales que tienen otro alineamiento son rarezas espeluznantes. Los ángeles, couatls y pegasos son celestiales'),

('Cieno', 'Criaturas gelatinosas que suelen carecer de una forma concreta. Casi siempre subterráneas, moran en cuevas y mazmorras, donde se alimentan de desechos, carroña o las criaturas que poseen la mala suerte de cruzarse en su camino. Los cienos más famosos son los púdines negros y los cubos gelatinosos'),

('Dragón', 'Enormes criaturas aladas de aspecto reptiliano, tremendamente poderosas y de orígenes antiguos. Los auténticos dragones, entre los que se cuentan tanto los metálicos, bondadosos, como los cromáticos, malvados, son seres muy inteligentes y con poderes mágicos innatos. Esta categoría también cubre otras criaturas emparentadas, aunque de forma lejana, con los verdaderos dragones. Menos poderosas e inteligentes, sus facultades mágicas son inferiores a las de sus primos los dragones auténticos. Ejemplos de estos seres son los guivernos y pseudodragones'),

('Elemental', 'Criaturas naturales de los Planos Elementales. Algunos de los monstruos de este tipo son poco más que una masa animada del elemento que encarnan. Los seres comúnmente llamados elementales son un ejemplo de esto. Otros, sin embargo, son entidades biológicas rebosantes de energía elemental. Las diversas razas de genios, entre las que se encuentran los djinns y los ifrits, han creado las civilizaciones más importantes de los Planos Elementales. Otros ejemplos de criaturas elementales serían los azers, los acechadores invisibles y los extraños de agua.'),

('Feérico', 'Criaturas mágicas fuertemente ligadas a las fuerzas de la naturaleza. Moran en las arboledas crepusculares y los bosques cubiertos de bruma. En ciertos mundos están fuertemente ligados al Feywild, que incluso reciben el nombre de Plano Feérico. Aunque también es posible hallar a estas criaturas en algunos Planos Exteriores, especialmente en Arbórea y las Tierras de las Bestias. Las dríades, los duendes y los sátiros son seres feéricos'),

('Gigante', 'Se alzan sobre los humanos y otras razas similares. Su forma es parecida a la humana, pero algunos poseen varias cabezas (los ettins) o deformidades (los fomoré). Las seis variedades de gigantes verdaderos son los gigantes de las colinas, de piedra, de escarcha, de fuego, de las nubes y de las tormentas. Además, hay otras criaturas que también son consideradas gigantes, como los ogros y los trolls');